### ISSUE TITLE
undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by ThaWeatherman** [EriHoss/giftoa#1]
```
$ giftoa -i dennis.gif -o dennis
/tmp/cchEiaUQ.o: In function `main':
program.c:(.text+0x175): undefined reference to `clock_gettime'
program.c:(.text+0x230): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
```

I installed everything through `apt-get` calls, then installed your stuff via a pip command in a virtualenv.

**Comment by EriHoss** [comment]
Thanks for the input

The C compiler may need to be passed the **-lrt** switch in order to link the real time library on your system.

Could you post the output of `cc -v` and distro if you don't mind?

Also maybe try compiling this small bit of C code with and without **-lrt** to see if it succeeds with it added or not.

```
#include <time.h>
#include <stdio.h>

int main(){
    struct timespec time;
    clock_gettime(CLOCK_MONOTONIC, &time);
    return 0;
}
```

Test 1) `cc test.c`

Test 2) `cc test.c -lrt`


Everything I have tested on had not required **-lrt**,  I don't believe it would harm anything to add it to 
the compile options for the small section of C code in giftoa even when it is not required.  I can tack it on the compile options inside the script if it works for you.

**Comment by EriHoss** [comment]
May also want to try that C code with this if adding **-lrt** does not work by itself.

`cc test.c -Wl,--no-as-needed -lrt`

**Comment by ThaWeatherman** [comment]
```
$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.6/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --progr
am-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib 
--enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --disable-werror --with-
arch-32=i686 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
```

```
$ cc test.c
/tmp/ccrOUcl6.o: In function `main':
test.c:(.text+0x19): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
```

The `-lrt` flags made it work though.

**Comment by ThaWeatherman** [comment]
I see the subprocess call on line 510. I should just be able to add the `-lrt` in there and have it work, right?

**Comment by ThaWeatherman** [comment]
Answered my own question. Got it working. Thanks!

**Comment by EriHoss** [comment]
No problem, I'll add this into the script as well.  Thanks for the help
